title: 览平科技工作室
description: 淘宝店铺

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

mathjax: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

google:
  gtag: G-W2V6CG5NF1
  adsense: ca-pub-2756917782318005
